apiVersion: v1
kind: Application
metadata:
  name: register-app-service
  labels:
    app: register-app 
spec:
  selector:
    app: register-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
